name: Daxa Analyzer release on PyPi
on:
  workflow_run:
      workflows: ["build"]
      branches: [main]
      types:
        - completed
jobs:
  release-on-pypi:
    runs-on: ubuntu-latest
    environment:
      name: qa
      url: https://test.pypi.org/p/daxa-analyzer-rc1
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v3
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish Daxa Distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
        
