name: Project release on PyPi

on:
  push:
    branches:
      - main
    tags:
      - "v[0-9].[0-9]+.[0-9]+*"

jobs:
  release-on-pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
